name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set IMAGE_TAG
      run: echo "IMAGE_TAG=main-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t abismohammad/node-metrics-app:${{ env.IMAGE_TAG }} .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image
      run: docker push abismohammad/node-metrics-app:${{ env.IMAGE_TAG }}

    - name: Update deployment repo
      run: |
        git clone https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/ABISMOHAMMAD/node-app-deploy.git
        cd node-app-deploy
        sed -i "s|image: abismohammad/node-metrics-app:.*|image: abismohammad/node-metrics-app:${{ env.IMAGE_TAG }}|" deployment.yml
        git config user.name "CI Bot"
        git config user.email "ci@github.com"
        git commit -am "Update image tag"
        git push

